
services:
  fastapi:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:80"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1
      - MONGO_URI=mongodb://mongo:27017
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 20G

  mongo:
    image: mongo:4.4
    container_name: mongo_db
    ports:
      - "8001:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 20G

  node:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: node_app
    ports:
      - "8002:3000"
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: bash -c "npm install && npm start"
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 25G

volumes:
  mongo_data:

networks:
  app-network: